### ISSUE TITLE
Add n/a label shortcut side of label search

### ISSUE THREAD

**Issue by Kefta** [jgchk/better-rym#105]
![image](https://user-images.githubusercontent.com/4593679/136432053-a48b69ef-e255-472a-945b-44511ac250fc.png)

On the left side of here so that it is unnecessary to search each time.

**Comment by Kefta** [comment]
Another n/a button could be added for the catalog number as a further convenience + standardising missing catalog numbers. A minority now use "none" which is carried over from Discogs, but n/a is the main standard.

**Comment by jgchk** [comment]
implemented in 6bd105b6e2844fe6edfc173c337efac0ca127dda
