### ISSUE TITLE
Add artist shortcut buttons for credits

### ISSUE THREAD

**Issue by Kefta** [jgchk/better-rym#106]
![image](https://user-images.githubusercontent.com/4593679/136435427-34ce8e62-59b0-4fb1-893f-4c9b55f27af5.png)

Either above or to the left, not sure what would work better for smaller resolutions. Specifically:
- "Unknown Artist" - shortcut to [unknown artist]
- "This Artist" - pulls the artist from the "File under" section to avoid having to scroll up and back down. If no artists are under this section, the button is disabled. If there's one artist, it's added directly to the credits. If there's more than one, open a small scroll menu that allows you to select which one to add. This is a bit involved so I can take it on when I know typescript better. For now, it could just add all the artists under "File under"

**Comment by jgchk** [comment]
implemented in c19ca93ac3dae29a430e59048150de8e982f345f
