### ISSUE TITLE
Can not import with spotify links

### ISSUE THREAD

**Issue by sakkarose** [jgchk/better-rym#119]
I have been using this extension for years and it was good. 
But today when i use spotify links for adding new release it says "Cannot read properties of undetified (reading 'sort').

**Comment by jgchk** [comment]
hi sakkarose, thanks for the report!

are you still having this issue? if so, could you send the spotify link for the release that won't import?

**Comment by sakkarose** [comment]
Oh, i just realize it happened when i use the link https://open.spotify.com/track/* instead of */album/*

**Comment by jgchk** [comment]
fixed in da61272477f37fa382db080a19b2310bb6b83a1e

should be updated on chrome & firefox later today :)
