### ISSUE TITLE
Automatically detect Creative Commons license on Bandcamp releases

### ISSUE THREAD

**Issue by guttitto** [jgchk/better-rym#120]
The automatic detection of some attributes on Discogs is quite useful. For Bandcamp, the detection of creative commons would probably rely on what is written on the bottom of the page. If it's written "all rights reserved" (default), no attribute. If it's written "some rights reserved", then the attribute applies, because it links to the CC license.
Some examples:
https://mattoc.bandcamp.com/album/butterfly - "all rights reserved" --> No attribute
https://hominiscanidae.bandcamp.com/album/colet-nea-de-anivers-rio-ano-i - "some rights reserved" --> [Creative Commons]

**Comment by jgchk** [comment]
solved in 7286e6edf040c21376a3d41e9fb4e85aa4e5a98e

**Comment by guttitto** [comment]
Thanks for the response!
I don't think it's working though :/
Tried it with 2 different bandcamp releases with CC license

**Comment by guttitto** [comment]
Thanks for the response!
Should it work automatically? I tried it before and after reinstalling the extension with multiple releases and it didn't add the attribute :/ maybe it has to do with being a performance attribute ?

**Comment by jgchk** [comment]
@guttitto howdy, i haven't pushed the update to chrome & firefox yet. got a few more changes i want to bundle in :)

i'll @ you here when i push it, but it should be up later tonight

**Comment by guttitto** [comment]
Fair enough, sorry 😅

**Comment by jgchk** [comment]
no worries!

**Comment by jgchk** [comment]
@guttitto update is up my friend!
