### ISSUE TITLE
Fixing formatting on spotify and getting rid of copyright + year from the label name

### ISSUE THREAD

**Issue by kopytko95** [jgchk/better-rym#128]
So that on spotify every " - Extended Mix" gets formated to (Extended Mix) and Every " - XYZ Remix" to (XYZ Remix)

My general idea is that the best way to recognize when it should be formated is to check whether after "-" it contains words like Mix, Remix, Edit, Rework/Re-Work, Remastered, Version, Cover, Acoustic, Stripped, Live - indicators from the top of my head for the stuff that generally should come in the ()'s and spotify gets them after -'s (thought maybe there's some better approach)

as for the second request
https://open.spotify.com/album/7sqgEXR77yYsrWlUFf6X8a
© 2016 Fueled By Ramen, LLC for the United States and WEA International Inc. for the world outside of the United States. A Warner Music Group Company. if whole expression gets pasted to label box, sometimes desired label don't come up - after removing © and year they eventually do

**Comment by jgchk** [comment]
added in 0688f7fde23dc062c5f6f84e6477eeaba3af8f4a and c1a89f6e815e82516eb0251bb9b6ffe499fb5a02
