### ISSUE TITLE
Set release type to DJ mix for 1-track SoundCloud imports with 20+ minutes

### ISSUE THREAD

**Issue by guttitto** [jgchk/better-rym#131]
Importing tracks from SoundCloud sets it to single by default, but I think it'd be nice if after a certain duration (I suggested 20 minutes but it can be more or less) it was changed to DJ mix, since SoundCloud is one of the main platforms for mixes and it's unusual for a single track to last that long.

**Comment by jgchk** [comment]
implemented in 5d20e92d962ef460b18406ea1240a494a53b0efc
