### ISSUE TITLE
Discogs import: Auto-set releases with a video format to [Video] release type

### ISSUE THREAD

**Issue by ThirdStrike3** [jgchk/better-rym#132]
Pure video formats are:

Blu-ray
DVD
DVD-R
Laserdisc
VCD 
Beta
VHS

The script currently sets these as [Album] release type, but any release in these format should have [Video] release type with no exceptions.

**Comment by jgchk** [comment]
solved in 681409f06545106e5868ef2a2cbfde3dc77005d6
