### ISSUE TITLE
Apple Music import: Wrong track numbers for multi-disc releases

### ISSUE THREAD

**Issue by ThirdStrike3** [jgchk/better-rym#133]
Multi disc releases (e.g. https://music.apple.com/us/album/scorpion/1418213110 ) should have track numbers like 1.1, 1.2, 1.3 etc for the first disc and 2.1, 2.2, 2.3 etc for the 2nd disc.

When I import multi-disc releases from Apple currently, it uses the regular 1, 2, 3 numbering for both discs.

what it is now:

![image](https://user-images.githubusercontent.com/106699798/171482717-a9790053-21a4-43db-b7fb-969591375be2.png)

what it should be:

![image](https://user-images.githubusercontent.com/106699798/171482906-a4a401d5-076d-44c4-9598-8532459c1c67.png)

**Comment by jgchk** [comment]
solved in f714b8ae2755aaedae5fccc1c9cab5ca48c1c1a3
