### ISSUE TITLE
Discogs import: Bolding headers in tracklists

### ISSUE THREAD

**Issue by ThirdStrike3** [jgchk/better-rym#134]
Headers in tracklists from discogs are imported but by RYM standards they should be bolded e.g. [b]Header[/b]

for https://www.discogs.com/release/13840777-NWA-Gangsta-Gangsta : 

this is how it is now:

![image](https://user-images.githubusercontent.com/106699798/171484977-1c14f6ed-6bec-4d14-9730-62f89975fba7.png)

this is how it should be:

![image](https://user-images.githubusercontent.com/106699798/171485055-51b280c5-86db-47c8-897a-835ad50225b0.png)

**Comment by jgchk** [comment]
solved in 74c2002cedcbf55d9e8c7ee6fffa1c52d086fc04
