### ISSUE TITLE
Beatport images upscaling

### ISSUE THREAD

**Issue by guttitto** [jgchk/better-rym#137]
As far as I know, the highest possible image ratio on Beatport is 1400x1400. There are even some releases that have images below that, like [this one](https://www.beatport.com/release/fire-bubbles-float-skin/922620), which has a 500x500 image... However, it seems that every image that you download from Beatport through BetterRYM gives you a 2400x2400 image, which means that they are probably being upscaled, and I think it would be best to just use the resolution which is available to us, as the extension already does with Apple Music and other services.

**Comment by kopytko95** [comment]
bump just in case

**Comment by jgchk** [comment]
solved in d510b6409a1f06145f1a4572eb509b5792a1b0f8
