### ISSUE TITLE
Discogs import: Give releases with the tag "Transcription" the promo attribute on rym

### ISSUE THREAD

**Issue by ThirdStrike3** [jgchk/better-rym#141]
e.g. https://www.discogs.com/release/13654006-Creedence-Clearwater-Revival-Untitled

"Transcription" releases are releases given to radio station for broadcast. RYM doesn't have a specific tag named this but the promo tag is the same thing so all these releases should have it.

**Comment by jgchk** [comment]
implemented in a7f15deb7432f7c9f0eba349cb5516fcc8bb82bb
