### ISSUE TITLE
Import Bandcamp timings when they're not displayed (yet)

### ISSUE THREAD

**Issue by revepastrop** [jgchk/better-rym#143]
Hi
Bandcamp pages have the annoying habit to somewhat "hide" timings for non-streamable tracks, be it for a pre-order or tracks that'll never stream. and better-rym imports info as it's currently displayed
now the interesting thing is that "hidden" timings get displayed if you choose the "embed this album" option & select "show tracklist", so is there a way for the script to catch & use those complete timings ?

**Comment by jgchk** [comment]
hi revepastrop, thanks for the report! i can definitely look into it. could you link an example bandcamp page that has nonstreamable tracks?

**Comment by revepastrop** [comment]
for instance something coming up next month
https://577records.bandcamp.com/album/toneflower

now if we use the embedded player, tadam, all timings are there
https://bandcamp.com/EmbeddedPlayer/album=3961711355/size=large/artwork=small

as for album number if needed, you can get it straight from main bandcamp page if you look for "item_id" in source code

**Comment by jgchk** [comment]
implemented in 716d4248ca9989f04ee0416ecde33ad99dec9a4d

**Comment by revepastrop** [comment]
thanks, will make our lives even better :)
