### ISSUE TITLE
Bug with hyphens in tracklist

### ISSUE THREAD

**Issue by sc113** [jgchk/better-rym#145]
https://www.beatport.com/release/everything-else-is-secondary/3305074

"Everything Else Is Secondary 1-800 Girls Remix" exported into "Everything Else Is Secondary (1 (800 Girls Remix))"

**Comment by sc113** [comment]
the same bug here: https://www.discogs.com/release/39463-Bolz-Bolz-Take-A-Walk-Remixes

**Comment by jgchk** [comment]
solved in 20e21ffe74ab67e2b3fafea5096efbde836ec592
