### ISSUE TITLE
Update to manifest v3

### ISSUE THREAD

**Issue by elliotchance** [jgchk/better-rym#146]
I get a warning about manifest v2 when installing the unpacked extension. See:

https://developer.chrome.com/blog/mv2-transition/

**Comment by jgchk** [comment]
conversion is mostly done in https://github.com/jgchk/better-rym/tree/manifest-v3

last big hurdle is losing `URL.createObjectURL` support in the background script -> service worker conversion, which was used for downloading cover art. there are some workarounds (https://bugs.chromium.org/p/chromium/issues/detail?id=1224027), though it may be easier just to rethink how we're downloading images in the first place

**Comment by Viktini** [comment]
Is this still in progress? Thought I'd ask since I'm using Vivaldi and the extension manager is nagging me in-browser, saying BetterRYM will no longer be supported soon.

**Comment by jgchk** [comment]
Just uploaded a manifest v3 version :heart:
