### ISSUE TITLE
BetterRYM doesn't catch all creative commons attributes on soundcloud

### ISSUE THREAD

**Issue by kopytko95** [jgchk/better-rym#155]
https://soundcloud.com/pyrox-music/pyrox-starlight
https://soundcloud.com/pyrox-music/pyrox-scraped
Pyrox - Scraped By Pyrox is licensed under a Creative Commons License, but it doesn't trigger BetterRYM in a way that adds the attribute to release

**Comment by jgchk** [comment]
implemented in b1833173dbed24bc980f7cc02354a2806319a260
