### ISSUE TITLE
Detect labels from Bandcamp

### ISSUE THREAD

**Issue by guttitto** [jgchk/better-rym#158]
As you likely know in a lot of releases on Bandcamp the label is present in a black box at the top right of the page, for instance:
https://oscaroscar.bandcamp.com/album/http404
**← more from Wichita Recordings**
source code: **"recordLabel":{"@type":"MusicGroup","name":"Wichita Recordings"**

https://oklou.bandcamp.com/album/galore-anniversary
**← more from Because Music**
source code: **"recordLabel":{"@type":"MusicGroup","name":"Because Music"**

**Comment by jgchk** [comment]
implemented in 908ec84e168fcf5696c00e1c5589a88d70a64967
