### ISSUE TITLE
Apple Music releases not working

### ISSUE THREAD

**Issue by KatyLB** [jgchk/better-rym#161]
Attempting to import information from Apple Music leads to a red "X" error. This is in Firefox and the script is up-to-date.

**Comment by jgchk** [comment]
Apple Music import is working fine on my end. wondering if this was a temporary outage or something

@KatyLB can you check whether this is still happening on your end? if so, a link to the specific Apple Music release that's failing would be helpful too

closing for now, but i'll reopen if you're still having problems
