### ISSUE TITLE
Not all numerals are capitalised

### ISSUE THREAD

**Issue by Wyyvern** [jgchk/better-rym#165]
When importing [this album](https://rateyourmusic.com/release/album/qstaw/malum-veneficus-viriditas-chronicles-ii/) the second track came through as 'Malum Veneficus Viriditas Chronicles II (Part Ii)', dunno if that's a one off unique example or if they're not kept capitalised if next to brackets. Letting you know anyways, thanks

**Comment by Wyyvern** [comment]
https://rateyourmusic.com/release/album/violet-light-and-a-hum/_mori-restat/

This got imported with Triptych Ii: Awareness and Triptych Iii: Blood Flow so I guess it's when there's a character after it, maybe before it too. Not a big issue, just bringing it up in the hopes it's an easy fix.

**Comment by jgchk** [comment]
solved in 036a713c6aa7b944f0e0269577c7cf5f0d93ea2f
