### ISSUE TITLE
Failed - network error on some images from bandcamp

### ISSUE THREAD

**Issue by kopytko95** [jgchk/better-rym#167]
https://nevrous.bandcamp.com/music
Extension Didn't work on none of black-red images but worked on the oldest three (white-ish), this also happens ocassionaly for other artists, for me it's exclusively from bandcamp, usually the big ones
![image](https://user-images.githubusercontent.com/64036105/207149513-ec78a73e-cdd6-4781-96c7-7c1d1d9dc7bf.png)

Usually when it's not working it's mostly for the images that are bigger (in space, not only on the resolution)

**Comment by jgchk** [comment]
these are downloading fine on my end. might've been a temporary issue

@kopytko95 same deal as https://github.com/jgchk/better-rym/issues/168, let me know if they still aren't working for you and i'll reopen this issue
