### ISSUE TITLE
Some cover arts from soundcloud don't download

### ISSUE THREAD

**Issue by kopytko95** [jgchk/better-rym#168]
https://soundcloud.com/ukelella/come-out-and-playyy

It's a minority of cases (i had like six in a row for this particular artist, even though for months there was no single issue with sc), so Im not even sure if it's worth fixing, but... there is an image, links in the source code doesn't differ very much from the ones that work, so why they dont?

**Comment by jgchk** [comment]
just checked and the cover art downloads fine on my end. might've just been a temporary issue?

@kopytko95 if you get a chance to recheck this and it still doesn't work on your end, let me know and i'll reopen this issue
