### ISSUE TITLE
Bandcamp icon has recently broken

### ISSUE THREAD

**Issue by Wyyvern** [jgchk/better-rym#171]
In the last few days, when a bandcamp link hasn't been added to a release, it'll say "Failed to get the VQD for query" when hovering over the icon and is unclickable, even when there's one available to add. After a link has been added, it works as normal.

**Comment by jgchk** [comment]
duckduckgo updated their VQD format which broke the regex we were using to detect it

solved in d737fa8207a06d6c4fa7011e2948583dbb4d433e
