### ISSUE TITLE
Bandcamp icon broke again in the same way

### ISSUE THREAD

**Issue by Wyyvern** [jgchk/better-rym#178]
https://github.com/jgchk/better-rym/issues/171

Same error as in Feb, another VQD query issue when the link hasn't been added yet.

**Comment by jgchk** [comment]
fixed in 813aba8f93d816618860cac46f5a3244d409136f

just uploaded the fix to chrome & firefox

**Comment by Wyyvern** [comment]
super quick, thanks ^^
