### ISSUE TITLE
Spotify is not including artists

### ISSUE THREAD

**Issue by elliotchance** [jgchk/better-rym#180]
Trying to load an album like https://open.spotify.com/album/0rttU2VExE9QVYa2pX3KDc does not include any artists.

**Comment by kopytko95** [comment]
Now if you want to submit regular album where's at least one featured artist/remixer
https://open.spotify.com/album/6rePArBMb5nLWEaY9aQqL4?si=dfVgbFdXTXG10rUJkh7ZXA it gets added this way
https://ibb.co/2YMHvjf
And it's great feature for VA comps, but they are rather minority of releases so i think it would work great as additional check for adding a release, and not done on default
