### ISSUE TITLE
Cover arts stopped downloading on itunes

### ISSUE THREAD

**Issue by kopytko95** [jgchk/better-rym#183]
When i add the link to the box and try to download, loading button gets into an endless loop, it might be temporary issue on their end, but it's been about 16 hours so maybe apple store had some slight revamp.
It happened very suddenly, i was filling casually some discography on artist and in the middle of it something happened
https://music.apple.com/us/album/burning-feat-rahiz-ep/1266835913
https://rateyourmusic.com/images/upload?type=l&assoc_id=15321268&replace_id=0
for quick look

**Comment by Gems7X** [comment]
Can confirm this is still an issue.

**Comment by jgchk** [comment]
solved in ca74c1460d9368df4d9a259cc2e9d94bb30f2a67
