### ISSUE TITLE
Unfilled bandcamp icon link led to buy action

### ISSUE THREAD

**Issue by Wyyvern** [jgchk/better-rym#186]
Tiny issue but not something I've seen before, the unfilled bandcamp icon on [this release](https://rateyourmusic.com/release/album/a-horrible-death-to-a-horrible-man/days-gone-by/) linked to
https://ahorribledeathtoahorribleman.bandcamp.com/album/days-gone-by?action=buy for some reason, not a big deal but might be worth adding ?action=buy and any other actions I'm not aware of to a blacklist to prevent any unintended actions.

**Comment by jgchk** [comment]
solved in 32dcfad
