### ISSUE TITLE
Spotify links are no longer imported

### ISSUE THREAD

**Issue by Forklift5** [jgchk/better-rym#190]
Some Spotify URLs now have a language/country part that make them unvalid (only playlists don't have that). Example:
Before: https://open.spotify.com/track/1PNk1Xno8t3spNEU78Hxsu
Now: https://open.spotify.com/intl-fr/track/1PNk1Xno8t3spNEU78Hxsu (France/French)

This may only affects the browser-based version (tested on Firefox PC and mobile)

**Comment by jgchk** [comment]
solved in 3945e22967459f2927f91b274c14e122dc88c9eb
