### ISSUE TITLE
Release import does not work any longer since rateyourmusic.com site update from 2024-12-10

### ISSUE THREAD

**Issue by FlorianWolters** [jgchk/better-rym#202]
Refer to https://rateyourmusic.com/development. I think the major aspect the import does not work any longer is the following:

> There is now a dedicated field to place English/Latin localized titles for releases where the primary title is in non-Latin script

![grafik](https://github.com/user-attachments/assets/16023998-8002-490e-b803-4bfcba526c46)

**Comment by Dan33185** [comment]
Having the same issue here

**Comment by uniwuni** [comment]
the main issue seems to be the artist -> artist performer change. ill try to tackle this today, if i'm lucky itll take about 5 minutes
