### ISSUE TITLE
"File under performer" gets duplicated when importing releases

### ISSUE THREAD

**Issue by Wyyvern** [jgchk/better-rym#205]
When clicking Import, it will activate the "search artists" box next to 1.3a and the top result is added to the submission as a second artist. Usually the same artist but when importing a release for [DIN](https://rateyourmusic.com/artist/din-7) it added the profile of a different [Din](https://rateyourmusic.com/artist/din_f1).

Clicking Import again will result in three artists, I'm used to giving it an extra click it when the page seems to be lagging.

Unticking artists in advanced options prevents it from happening, but it looks unintended to begin with, guessing it's a side effect of the recent update.

**Comment by kopytko95** [comment]
+1

**Comment by Wyyvern** [comment]
Looks like the last update fixed it, thanks!
