### ISSUE TITLE
adds long spaces to covers from Apple Music

### ISSUE THREAD

**Issue by jgchk** [jgchk/better-rym#34]

**Comment by sc113** [comment]
Spaces killed file extensions: 
https://music.apple.com/us/album/nightdrive-1984-mix-single/1554602967
https://music.apple.com/us/album/walking-alone-single/494175743

Just spaces in the file names:
https://music.apple.com/ru/album/ubiquity-feat-breakbot-the-magician-remix-single/1553206599
https://music.apple.com/ru/album/feed-the-fire-kassian-remix-single/1539458884
https://music.apple.com/us/album/better-day-feat-rudy/319583890
