### ISSUE TITLE
import not working when "various artists" release type selected

### ISSUE THREAD

**Issue by sc113** [jgchk/better-rym#36]

**Comment by jgchk** [comment]
@sc113 I can't reproduce this on my end. Can you provide specific steps to reproduce?

**Comment by sc113** [comment]
I guess it's a case when you try to add release via various artists page - https://rateyourmusic.com/various_artists/ (-> Add a new V/A release) or via direct link https://rateyourmusic.com/releases/ac?artist_id=5

**Comment by jgchk** [comment]
ahh got it. looks like the script fails when it tries to add "Various Artists" to the File Under section. 

we should allow failures here and just continue filling the form
