### ISSUE TITLE
So that you can add youtube playlist as an album

### ISSUE THREAD

**Issue by kopytko95** [jgchk/better-rym#74]
Like this one
https://www.youtube.com/watch?v=fPfhcyC0ZhY&list=PLcFGX0YNxApDdutB6FsK6g5Tn6LiYz6Mx&ab_channel=VandalVibeVandalVibe
Track number based on the position of tracklist, track length is visible so (I hope) it can be imported too, and whole title might go as track name.

**Comment by jgchk** [comment]
this should definitely be included - putting at the top of my feature list. thanks for the request :)
