### ISSUE TITLE
importing label from digital services

### ISSUE THREAD

**Issue by kopytko95** [jgchk/better-rym#75]
from itunes/spotify it would be cool if it could also import copyright info to label field. If there's actually the label name in the field, i can just click search button instead of copying/writing it everytime (especially arduous while filling label's catalog, for example)

**Comment by kopytko95** [comment]
Even if, like in this example
https://open.spotify.com/album/71SNdHRiXYSHPePDk9gCCD whole
"Marceli Bober, under exclusive license to Universal Music Polska" appears on the field, desired label comes up anyway.
And if there was only eg. artist's name there, or some random numbers put by distributor, it wouldn't have any negative effect if just appears there

**Comment by jgchk** [comment]
great idea!

I had avoided auto-adding labels due to the issue you mention. Another case is Spotify self-published releases where artists can basically put in whatever they want for the copyright field.

just filling out the label search box but not actually adding a label is a good compromise
