### ISSUE TITLE
Releases coming up in YouTube search history

### ISSUE THREAD

**Issue by Gems7X** [jgchk/better-rym#76]
Whenever I click on a release it always adds it to my YouTube search history, it's nothing too terrible just can be annoying haha

**Comment by jgchk** [comment]
yeah I'd like to find a workaround for this

right now we're essentially loading youtube in the background and typing into the search bar automatically as a way to get around Youtube's API rate limiting

**Comment by Gems7X** [comment]
cheers for replying so quickly! i'm sure you'll find a way aroud it 👍

**Comment by jgchk** [comment]
solved in 35c82669c1755b20f048f9c27ba30753ddcb1bc2
