### ISSUE TITLE
"Mix" is capitalizing

### ISSUE THREAD

**Issue by sc113** [jgchk/better-rym#77]
The bug occurs in this release: https://open.spotify.com/album/6zwnIj1QgilV3z3ffQEenn.

**Comment by jgchk** [comment]
for documentation purposes:
Mix is being capitalized as if it were a Roman Numeral
"Vocal Mix" -> "Vocal MIX"

probably just need to add it to a list of words to exclude from being detected as a Roman Numeral

**Comment by kopytko95** [comment]
Would it be possible to also add "Mi" as an exception for roman numerals? Word means "to me" as in "give it to me" and is commonly used

**Comment by jgchk** [comment]
fixed by a6e3efa
