### ISSUE TITLE
Discogs support doesn't work on some releases

### ISSUE THREAD

**Issue by kopytko95** [jgchk/better-rym#84]
Extension doesnt work on some releases

It's unexpected, because old version (the discontinued one, i still sometimes use it) works here. Could it be the demo attribute that messes with the extension?
https://www.discogs.com/HDS-Parodos/release/11224852 as example

EDIT: https://www.discogs.com/Jahoo-Dobre-s%C5%82owo-/release/13639917 another album that doesn't work, so it;s no demo attribute, but some releases work

**Comment by jgchk** [comment]
weird.

im out of town this weekend but ill take a look asap

**Comment by jgchk** [comment]
fixed by 5659b19
